name: commit
description: "A Flutter-based offline-first app inspired by Loop Habit Tracker to help you commit to your goals."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.1.0
  intl: ^0.19.0

  # Database
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_heatmap_calendar: ^1.0.4
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^3.0.0
  timezone: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  drift_dev: ^2.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/
